// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_messages_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_messages_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_messages_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_messages_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_messages_2eproto;
namespace railway {
class Message;
class MessageDefaultTypeInternal;
extern MessageDefaultTypeInternal _Message_default_instance_;
class TrainCommand;
class TrainCommandDefaultTypeInternal;
extern TrainCommandDefaultTypeInternal _TrainCommand_default_instance_;
class TrainStatus;
class TrainStatusDefaultTypeInternal;
extern TrainStatusDefaultTypeInternal _TrainStatus_default_instance_;
}  // namespace railway
PROTOBUF_NAMESPACE_OPEN
template<> ::railway::Message* Arena::CreateMaybeMessage<::railway::Message>(Arena*);
template<> ::railway::TrainCommand* Arena::CreateMaybeMessage<::railway::TrainCommand>(Arena*);
template<> ::railway::TrainStatus* Arena::CreateMaybeMessage<::railway::TrainStatus>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace railway {

enum TrainCommand_CommandType : int {
  TrainCommand_CommandType_ACCELERATE = 0,
  TrainCommand_CommandType_BRAKE = 1,
  TrainCommand_CommandType_STOP = 2,
  TrainCommand_CommandType_EMERGENCY_STOP = 3,
  TrainCommand_CommandType_TrainCommand_CommandType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  TrainCommand_CommandType_TrainCommand_CommandType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool TrainCommand_CommandType_IsValid(int value);
constexpr TrainCommand_CommandType TrainCommand_CommandType_CommandType_MIN = TrainCommand_CommandType_ACCELERATE;
constexpr TrainCommand_CommandType TrainCommand_CommandType_CommandType_MAX = TrainCommand_CommandType_EMERGENCY_STOP;
constexpr int TrainCommand_CommandType_CommandType_ARRAYSIZE = TrainCommand_CommandType_CommandType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* TrainCommand_CommandType_descriptor();
template<typename T>
inline const std::string& TrainCommand_CommandType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, TrainCommand_CommandType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function TrainCommand_CommandType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    TrainCommand_CommandType_descriptor(), enum_t_value);
}
inline bool TrainCommand_CommandType_Parse(
    const std::string& name, TrainCommand_CommandType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<TrainCommand_CommandType>(
    TrainCommand_CommandType_descriptor(), name, value);
}
enum TrainStatus_StatusCode : int {
  TrainStatus_StatusCode_NORMAL = 0,
  TrainStatus_StatusCode_WARNING = 1,
  TrainStatus_StatusCode_ERROR = 2,
  TrainStatus_StatusCode_EMERGENCY = 3,
  TrainStatus_StatusCode_TrainStatus_StatusCode_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  TrainStatus_StatusCode_TrainStatus_StatusCode_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool TrainStatus_StatusCode_IsValid(int value);
constexpr TrainStatus_StatusCode TrainStatus_StatusCode_StatusCode_MIN = TrainStatus_StatusCode_NORMAL;
constexpr TrainStatus_StatusCode TrainStatus_StatusCode_StatusCode_MAX = TrainStatus_StatusCode_EMERGENCY;
constexpr int TrainStatus_StatusCode_StatusCode_ARRAYSIZE = TrainStatus_StatusCode_StatusCode_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* TrainStatus_StatusCode_descriptor();
template<typename T>
inline const std::string& TrainStatus_StatusCode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, TrainStatus_StatusCode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function TrainStatus_StatusCode_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    TrainStatus_StatusCode_descriptor(), enum_t_value);
}
inline bool TrainStatus_StatusCode_Parse(
    const std::string& name, TrainStatus_StatusCode* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<TrainStatus_StatusCode>(
    TrainStatus_StatusCode_descriptor(), name, value);
}
// ===================================================================

class TrainCommand PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:railway.TrainCommand) */ {
 public:
  inline TrainCommand() : TrainCommand(nullptr) {};
  virtual ~TrainCommand();

  TrainCommand(const TrainCommand& from);
  TrainCommand(TrainCommand&& from) noexcept
    : TrainCommand() {
    *this = ::std::move(from);
  }

  inline TrainCommand& operator=(const TrainCommand& from) {
    CopyFrom(from);
    return *this;
  }
  inline TrainCommand& operator=(TrainCommand&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TrainCommand& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TrainCommand* internal_default_instance() {
    return reinterpret_cast<const TrainCommand*>(
               &_TrainCommand_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TrainCommand& a, TrainCommand& b) {
    a.Swap(&b);
  }
  inline void Swap(TrainCommand* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TrainCommand* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TrainCommand* New() const final {
    return CreateMaybeMessage<TrainCommand>(nullptr);
  }

  TrainCommand* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TrainCommand>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TrainCommand& from);
  void MergeFrom(const TrainCommand& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TrainCommand* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "railway.TrainCommand";
  }
  protected:
  explicit TrainCommand(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_messages_2eproto);
    return ::descriptor_table_messages_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef TrainCommand_CommandType CommandType;
  static constexpr CommandType ACCELERATE =
    TrainCommand_CommandType_ACCELERATE;
  static constexpr CommandType BRAKE =
    TrainCommand_CommandType_BRAKE;
  static constexpr CommandType STOP =
    TrainCommand_CommandType_STOP;
  static constexpr CommandType EMERGENCY_STOP =
    TrainCommand_CommandType_EMERGENCY_STOP;
  static inline bool CommandType_IsValid(int value) {
    return TrainCommand_CommandType_IsValid(value);
  }
  static constexpr CommandType CommandType_MIN =
    TrainCommand_CommandType_CommandType_MIN;
  static constexpr CommandType CommandType_MAX =
    TrainCommand_CommandType_CommandType_MAX;
  static constexpr int CommandType_ARRAYSIZE =
    TrainCommand_CommandType_CommandType_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  CommandType_descriptor() {
    return TrainCommand_CommandType_descriptor();
  }
  template<typename T>
  static inline const std::string& CommandType_Name(T enum_t_value) {
    static_assert(::std::is_same<T, CommandType>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function CommandType_Name.");
    return TrainCommand_CommandType_Name(enum_t_value);
  }
  static inline bool CommandType_Parse(const std::string& name,
      CommandType* value) {
    return TrainCommand_CommandType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kTrainIdFieldNumber = 1,
    kTargetSpeedFieldNumber = 3,
    kTimestampFieldNumber = 4,
    kCommandFieldNumber = 2,
  };
  // string train_id = 1;
  void clear_train_id();
  const std::string& train_id() const;
  void set_train_id(const std::string& value);
  void set_train_id(std::string&& value);
  void set_train_id(const char* value);
  void set_train_id(const char* value, size_t size);
  std::string* mutable_train_id();
  std::string* release_train_id();
  void set_allocated_train_id(std::string* train_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_train_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_train_id(
      std::string* train_id);
  private:
  const std::string& _internal_train_id() const;
  void _internal_set_train_id(const std::string& value);
  std::string* _internal_mutable_train_id();
  public:

  // double target_speed = 3;
  void clear_target_speed();
  double target_speed() const;
  void set_target_speed(double value);
  private:
  double _internal_target_speed() const;
  void _internal_set_target_speed(double value);
  public:

  // int64 timestamp = 4;
  void clear_timestamp();
  ::PROTOBUF_NAMESPACE_ID::int64 timestamp() const;
  void set_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_timestamp() const;
  void _internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // .railway.TrainCommand.CommandType command = 2;
  void clear_command();
  ::railway::TrainCommand_CommandType command() const;
  void set_command(::railway::TrainCommand_CommandType value);
  private:
  ::railway::TrainCommand_CommandType _internal_command() const;
  void _internal_set_command(::railway::TrainCommand_CommandType value);
  public:

  // @@protoc_insertion_point(class_scope:railway.TrainCommand)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr train_id_;
  double target_speed_;
  ::PROTOBUF_NAMESPACE_ID::int64 timestamp_;
  int command_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_messages_2eproto;
};
// -------------------------------------------------------------------

class TrainStatus PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:railway.TrainStatus) */ {
 public:
  inline TrainStatus() : TrainStatus(nullptr) {};
  virtual ~TrainStatus();

  TrainStatus(const TrainStatus& from);
  TrainStatus(TrainStatus&& from) noexcept
    : TrainStatus() {
    *this = ::std::move(from);
  }

  inline TrainStatus& operator=(const TrainStatus& from) {
    CopyFrom(from);
    return *this;
  }
  inline TrainStatus& operator=(TrainStatus&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TrainStatus& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TrainStatus* internal_default_instance() {
    return reinterpret_cast<const TrainStatus*>(
               &_TrainStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(TrainStatus& a, TrainStatus& b) {
    a.Swap(&b);
  }
  inline void Swap(TrainStatus* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TrainStatus* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TrainStatus* New() const final {
    return CreateMaybeMessage<TrainStatus>(nullptr);
  }

  TrainStatus* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TrainStatus>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TrainStatus& from);
  void MergeFrom(const TrainStatus& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TrainStatus* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "railway.TrainStatus";
  }
  protected:
  explicit TrainStatus(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_messages_2eproto);
    return ::descriptor_table_messages_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef TrainStatus_StatusCode StatusCode;
  static constexpr StatusCode NORMAL =
    TrainStatus_StatusCode_NORMAL;
  static constexpr StatusCode WARNING =
    TrainStatus_StatusCode_WARNING;
  static constexpr StatusCode ERROR =
    TrainStatus_StatusCode_ERROR;
  static constexpr StatusCode EMERGENCY =
    TrainStatus_StatusCode_EMERGENCY;
  static inline bool StatusCode_IsValid(int value) {
    return TrainStatus_StatusCode_IsValid(value);
  }
  static constexpr StatusCode StatusCode_MIN =
    TrainStatus_StatusCode_StatusCode_MIN;
  static constexpr StatusCode StatusCode_MAX =
    TrainStatus_StatusCode_StatusCode_MAX;
  static constexpr int StatusCode_ARRAYSIZE =
    TrainStatus_StatusCode_StatusCode_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  StatusCode_descriptor() {
    return TrainStatus_StatusCode_descriptor();
  }
  template<typename T>
  static inline const std::string& StatusCode_Name(T enum_t_value) {
    static_assert(::std::is_same<T, StatusCode>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function StatusCode_Name.");
    return TrainStatus_StatusCode_Name(enum_t_value);
  }
  static inline bool StatusCode_Parse(const std::string& name,
      StatusCode* value) {
    return TrainStatus_StatusCode_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kWarningsFieldNumber = 6,
    kTrainIdFieldNumber = 1,
    kCurrentSpeedFieldNumber = 2,
    kPositionFieldNumber = 3,
    kTimestampFieldNumber = 5,
    kStatusFieldNumber = 4,
  };
  // repeated string warnings = 6;
  int warnings_size() const;
  private:
  int _internal_warnings_size() const;
  public:
  void clear_warnings();
  const std::string& warnings(int index) const;
  std::string* mutable_warnings(int index);
  void set_warnings(int index, const std::string& value);
  void set_warnings(int index, std::string&& value);
  void set_warnings(int index, const char* value);
  void set_warnings(int index, const char* value, size_t size);
  std::string* add_warnings();
  void add_warnings(const std::string& value);
  void add_warnings(std::string&& value);
  void add_warnings(const char* value);
  void add_warnings(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& warnings() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_warnings();
  private:
  const std::string& _internal_warnings(int index) const;
  std::string* _internal_add_warnings();
  public:

  // string train_id = 1;
  void clear_train_id();
  const std::string& train_id() const;
  void set_train_id(const std::string& value);
  void set_train_id(std::string&& value);
  void set_train_id(const char* value);
  void set_train_id(const char* value, size_t size);
  std::string* mutable_train_id();
  std::string* release_train_id();
  void set_allocated_train_id(std::string* train_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_train_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_train_id(
      std::string* train_id);
  private:
  const std::string& _internal_train_id() const;
  void _internal_set_train_id(const std::string& value);
  std::string* _internal_mutable_train_id();
  public:

  // double current_speed = 2;
  void clear_current_speed();
  double current_speed() const;
  void set_current_speed(double value);
  private:
  double _internal_current_speed() const;
  void _internal_set_current_speed(double value);
  public:

  // double position = 3;
  void clear_position();
  double position() const;
  void set_position(double value);
  private:
  double _internal_position() const;
  void _internal_set_position(double value);
  public:

  // int64 timestamp = 5;
  void clear_timestamp();
  ::PROTOBUF_NAMESPACE_ID::int64 timestamp() const;
  void set_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_timestamp() const;
  void _internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // .railway.TrainStatus.StatusCode status = 4;
  void clear_status();
  ::railway::TrainStatus_StatusCode status() const;
  void set_status(::railway::TrainStatus_StatusCode value);
  private:
  ::railway::TrainStatus_StatusCode _internal_status() const;
  void _internal_set_status(::railway::TrainStatus_StatusCode value);
  public:

  // @@protoc_insertion_point(class_scope:railway.TrainStatus)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> warnings_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr train_id_;
  double current_speed_;
  double position_;
  ::PROTOBUF_NAMESPACE_ID::int64 timestamp_;
  int status_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_messages_2eproto;
};
// -------------------------------------------------------------------

class Message PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:railway.Message) */ {
 public:
  inline Message() : Message(nullptr) {};
  virtual ~Message();

  Message(const Message& from);
  Message(Message&& from) noexcept
    : Message() {
    *this = ::std::move(from);
  }

  inline Message& operator=(const Message& from) {
    CopyFrom(from);
    return *this;
  }
  inline Message& operator=(Message&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Message& default_instance();

  enum PayloadCase {
    kCommand = 1,
    kStatus = 2,
    PAYLOAD_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Message* internal_default_instance() {
    return reinterpret_cast<const Message*>(
               &_Message_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Message& a, Message& b) {
    a.Swap(&b);
  }
  inline void Swap(Message* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Message* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Message* New() const final {
    return CreateMaybeMessage<Message>(nullptr);
  }

  Message* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Message>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Message& from);
  void MergeFrom(const Message& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Message* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "railway.Message";
  }
  protected:
  explicit Message(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_messages_2eproto);
    return ::descriptor_table_messages_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCommandFieldNumber = 1,
    kStatusFieldNumber = 2,
  };
  // .railway.TrainCommand command = 1;
  bool has_command() const;
  private:
  bool _internal_has_command() const;
  public:
  void clear_command();
  const ::railway::TrainCommand& command() const;
  ::railway::TrainCommand* release_command();
  ::railway::TrainCommand* mutable_command();
  void set_allocated_command(::railway::TrainCommand* command);
  private:
  const ::railway::TrainCommand& _internal_command() const;
  ::railway::TrainCommand* _internal_mutable_command();
  public:
  void unsafe_arena_set_allocated_command(
      ::railway::TrainCommand* command);
  ::railway::TrainCommand* unsafe_arena_release_command();

  // .railway.TrainStatus status = 2;
  bool has_status() const;
  private:
  bool _internal_has_status() const;
  public:
  void clear_status();
  const ::railway::TrainStatus& status() const;
  ::railway::TrainStatus* release_status();
  ::railway::TrainStatus* mutable_status();
  void set_allocated_status(::railway::TrainStatus* status);
  private:
  const ::railway::TrainStatus& _internal_status() const;
  ::railway::TrainStatus* _internal_mutable_status();
  public:
  void unsafe_arena_set_allocated_status(
      ::railway::TrainStatus* status);
  ::railway::TrainStatus* unsafe_arena_release_status();

  void clear_payload();
  PayloadCase payload_case() const;
  // @@protoc_insertion_point(class_scope:railway.Message)
 private:
  class _Internal;
  void set_has_command();
  void set_has_status();

  inline bool has_payload() const;
  inline void clear_has_payload();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  union PayloadUnion {
    PayloadUnion() {}
    ::railway::TrainCommand* command_;
    ::railway::TrainStatus* status_;
  } payload_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::uint32 _oneof_case_[1];

  friend struct ::TableStruct_messages_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TrainCommand

// string train_id = 1;
inline void TrainCommand::clear_train_id() {
  train_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& TrainCommand::train_id() const {
  // @@protoc_insertion_point(field_get:railway.TrainCommand.train_id)
  return _internal_train_id();
}
inline void TrainCommand::set_train_id(const std::string& value) {
  _internal_set_train_id(value);
  // @@protoc_insertion_point(field_set:railway.TrainCommand.train_id)
}
inline std::string* TrainCommand::mutable_train_id() {
  // @@protoc_insertion_point(field_mutable:railway.TrainCommand.train_id)
  return _internal_mutable_train_id();
}
inline const std::string& TrainCommand::_internal_train_id() const {
  return train_id_.Get();
}
inline void TrainCommand::_internal_set_train_id(const std::string& value) {
  
  train_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void TrainCommand::set_train_id(std::string&& value) {
  
  train_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:railway.TrainCommand.train_id)
}
inline void TrainCommand::set_train_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  train_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:railway.TrainCommand.train_id)
}
inline void TrainCommand::set_train_id(const char* value,
    size_t size) {
  
  train_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:railway.TrainCommand.train_id)
}
inline std::string* TrainCommand::_internal_mutable_train_id() {
  
  return train_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* TrainCommand::release_train_id() {
  // @@protoc_insertion_point(field_release:railway.TrainCommand.train_id)
  return train_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void TrainCommand::set_allocated_train_id(std::string* train_id) {
  if (train_id != nullptr) {
    
  } else {
    
  }
  train_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), train_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:railway.TrainCommand.train_id)
}
inline std::string* TrainCommand::unsafe_arena_release_train_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:railway.TrainCommand.train_id)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return train_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void TrainCommand::unsafe_arena_set_allocated_train_id(
    std::string* train_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (train_id != nullptr) {
    
  } else {
    
  }
  train_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      train_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:railway.TrainCommand.train_id)
}

// .railway.TrainCommand.CommandType command = 2;
inline void TrainCommand::clear_command() {
  command_ = 0;
}
inline ::railway::TrainCommand_CommandType TrainCommand::_internal_command() const {
  return static_cast< ::railway::TrainCommand_CommandType >(command_);
}
inline ::railway::TrainCommand_CommandType TrainCommand::command() const {
  // @@protoc_insertion_point(field_get:railway.TrainCommand.command)
  return _internal_command();
}
inline void TrainCommand::_internal_set_command(::railway::TrainCommand_CommandType value) {
  
  command_ = value;
}
inline void TrainCommand::set_command(::railway::TrainCommand_CommandType value) {
  _internal_set_command(value);
  // @@protoc_insertion_point(field_set:railway.TrainCommand.command)
}

// double target_speed = 3;
inline void TrainCommand::clear_target_speed() {
  target_speed_ = 0;
}
inline double TrainCommand::_internal_target_speed() const {
  return target_speed_;
}
inline double TrainCommand::target_speed() const {
  // @@protoc_insertion_point(field_get:railway.TrainCommand.target_speed)
  return _internal_target_speed();
}
inline void TrainCommand::_internal_set_target_speed(double value) {
  
  target_speed_ = value;
}
inline void TrainCommand::set_target_speed(double value) {
  _internal_set_target_speed(value);
  // @@protoc_insertion_point(field_set:railway.TrainCommand.target_speed)
}

// int64 timestamp = 4;
inline void TrainCommand::clear_timestamp() {
  timestamp_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 TrainCommand::_internal_timestamp() const {
  return timestamp_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 TrainCommand::timestamp() const {
  // @@protoc_insertion_point(field_get:railway.TrainCommand.timestamp)
  return _internal_timestamp();
}
inline void TrainCommand::_internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  timestamp_ = value;
}
inline void TrainCommand::set_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:railway.TrainCommand.timestamp)
}

// -------------------------------------------------------------------

// TrainStatus

// string train_id = 1;
inline void TrainStatus::clear_train_id() {
  train_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& TrainStatus::train_id() const {
  // @@protoc_insertion_point(field_get:railway.TrainStatus.train_id)
  return _internal_train_id();
}
inline void TrainStatus::set_train_id(const std::string& value) {
  _internal_set_train_id(value);
  // @@protoc_insertion_point(field_set:railway.TrainStatus.train_id)
}
inline std::string* TrainStatus::mutable_train_id() {
  // @@protoc_insertion_point(field_mutable:railway.TrainStatus.train_id)
  return _internal_mutable_train_id();
}
inline const std::string& TrainStatus::_internal_train_id() const {
  return train_id_.Get();
}
inline void TrainStatus::_internal_set_train_id(const std::string& value) {
  
  train_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void TrainStatus::set_train_id(std::string&& value) {
  
  train_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:railway.TrainStatus.train_id)
}
inline void TrainStatus::set_train_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  train_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:railway.TrainStatus.train_id)
}
inline void TrainStatus::set_train_id(const char* value,
    size_t size) {
  
  train_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:railway.TrainStatus.train_id)
}
inline std::string* TrainStatus::_internal_mutable_train_id() {
  
  return train_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* TrainStatus::release_train_id() {
  // @@protoc_insertion_point(field_release:railway.TrainStatus.train_id)
  return train_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void TrainStatus::set_allocated_train_id(std::string* train_id) {
  if (train_id != nullptr) {
    
  } else {
    
  }
  train_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), train_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:railway.TrainStatus.train_id)
}
inline std::string* TrainStatus::unsafe_arena_release_train_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:railway.TrainStatus.train_id)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return train_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void TrainStatus::unsafe_arena_set_allocated_train_id(
    std::string* train_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (train_id != nullptr) {
    
  } else {
    
  }
  train_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      train_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:railway.TrainStatus.train_id)
}

// double current_speed = 2;
inline void TrainStatus::clear_current_speed() {
  current_speed_ = 0;
}
inline double TrainStatus::_internal_current_speed() const {
  return current_speed_;
}
inline double TrainStatus::current_speed() const {
  // @@protoc_insertion_point(field_get:railway.TrainStatus.current_speed)
  return _internal_current_speed();
}
inline void TrainStatus::_internal_set_current_speed(double value) {
  
  current_speed_ = value;
}
inline void TrainStatus::set_current_speed(double value) {
  _internal_set_current_speed(value);
  // @@protoc_insertion_point(field_set:railway.TrainStatus.current_speed)
}

// double position = 3;
inline void TrainStatus::clear_position() {
  position_ = 0;
}
inline double TrainStatus::_internal_position() const {
  return position_;
}
inline double TrainStatus::position() const {
  // @@protoc_insertion_point(field_get:railway.TrainStatus.position)
  return _internal_position();
}
inline void TrainStatus::_internal_set_position(double value) {
  
  position_ = value;
}
inline void TrainStatus::set_position(double value) {
  _internal_set_position(value);
  // @@protoc_insertion_point(field_set:railway.TrainStatus.position)
}

// .railway.TrainStatus.StatusCode status = 4;
inline void TrainStatus::clear_status() {
  status_ = 0;
}
inline ::railway::TrainStatus_StatusCode TrainStatus::_internal_status() const {
  return static_cast< ::railway::TrainStatus_StatusCode >(status_);
}
inline ::railway::TrainStatus_StatusCode TrainStatus::status() const {
  // @@protoc_insertion_point(field_get:railway.TrainStatus.status)
  return _internal_status();
}
inline void TrainStatus::_internal_set_status(::railway::TrainStatus_StatusCode value) {
  
  status_ = value;
}
inline void TrainStatus::set_status(::railway::TrainStatus_StatusCode value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:railway.TrainStatus.status)
}

// int64 timestamp = 5;
inline void TrainStatus::clear_timestamp() {
  timestamp_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 TrainStatus::_internal_timestamp() const {
  return timestamp_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 TrainStatus::timestamp() const {
  // @@protoc_insertion_point(field_get:railway.TrainStatus.timestamp)
  return _internal_timestamp();
}
inline void TrainStatus::_internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  timestamp_ = value;
}
inline void TrainStatus::set_timestamp(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:railway.TrainStatus.timestamp)
}

// repeated string warnings = 6;
inline int TrainStatus::_internal_warnings_size() const {
  return warnings_.size();
}
inline int TrainStatus::warnings_size() const {
  return _internal_warnings_size();
}
inline void TrainStatus::clear_warnings() {
  warnings_.Clear();
}
inline std::string* TrainStatus::add_warnings() {
  // @@protoc_insertion_point(field_add_mutable:railway.TrainStatus.warnings)
  return _internal_add_warnings();
}
inline const std::string& TrainStatus::_internal_warnings(int index) const {
  return warnings_.Get(index);
}
inline const std::string& TrainStatus::warnings(int index) const {
  // @@protoc_insertion_point(field_get:railway.TrainStatus.warnings)
  return _internal_warnings(index);
}
inline std::string* TrainStatus::mutable_warnings(int index) {
  // @@protoc_insertion_point(field_mutable:railway.TrainStatus.warnings)
  return warnings_.Mutable(index);
}
inline void TrainStatus::set_warnings(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:railway.TrainStatus.warnings)
  warnings_.Mutable(index)->assign(value);
}
inline void TrainStatus::set_warnings(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:railway.TrainStatus.warnings)
  warnings_.Mutable(index)->assign(std::move(value));
}
inline void TrainStatus::set_warnings(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  warnings_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:railway.TrainStatus.warnings)
}
inline void TrainStatus::set_warnings(int index, const char* value, size_t size) {
  warnings_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:railway.TrainStatus.warnings)
}
inline std::string* TrainStatus::_internal_add_warnings() {
  return warnings_.Add();
}
inline void TrainStatus::add_warnings(const std::string& value) {
  warnings_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:railway.TrainStatus.warnings)
}
inline void TrainStatus::add_warnings(std::string&& value) {
  warnings_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:railway.TrainStatus.warnings)
}
inline void TrainStatus::add_warnings(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  warnings_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:railway.TrainStatus.warnings)
}
inline void TrainStatus::add_warnings(const char* value, size_t size) {
  warnings_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:railway.TrainStatus.warnings)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
TrainStatus::warnings() const {
  // @@protoc_insertion_point(field_list:railway.TrainStatus.warnings)
  return warnings_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
TrainStatus::mutable_warnings() {
  // @@protoc_insertion_point(field_mutable_list:railway.TrainStatus.warnings)
  return &warnings_;
}

// -------------------------------------------------------------------

// Message

// .railway.TrainCommand command = 1;
inline bool Message::_internal_has_command() const {
  return payload_case() == kCommand;
}
inline bool Message::has_command() const {
  return _internal_has_command();
}
inline void Message::set_has_command() {
  _oneof_case_[0] = kCommand;
}
inline void Message::clear_command() {
  if (_internal_has_command()) {
    if (GetArena() == nullptr) {
      delete payload_.command_;
    }
    clear_has_payload();
  }
}
inline ::railway::TrainCommand* Message::release_command() {
  // @@protoc_insertion_point(field_release:railway.Message.command)
  if (_internal_has_command()) {
    clear_has_payload();
      ::railway::TrainCommand* temp = payload_.command_;
    if (GetArena() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    payload_.command_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::railway::TrainCommand& Message::_internal_command() const {
  return _internal_has_command()
      ? *payload_.command_
      : *reinterpret_cast< ::railway::TrainCommand*>(&::railway::_TrainCommand_default_instance_);
}
inline const ::railway::TrainCommand& Message::command() const {
  // @@protoc_insertion_point(field_get:railway.Message.command)
  return _internal_command();
}
inline ::railway::TrainCommand* Message::unsafe_arena_release_command() {
  // @@protoc_insertion_point(field_unsafe_arena_release:railway.Message.command)
  if (_internal_has_command()) {
    clear_has_payload();
    ::railway::TrainCommand* temp = payload_.command_;
    payload_.command_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Message::unsafe_arena_set_allocated_command(::railway::TrainCommand* command) {
  clear_payload();
  if (command) {
    set_has_command();
    payload_.command_ = command;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:railway.Message.command)
}
inline ::railway::TrainCommand* Message::_internal_mutable_command() {
  if (!_internal_has_command()) {
    clear_payload();
    set_has_command();
    payload_.command_ = CreateMaybeMessage< ::railway::TrainCommand >(GetArena());
  }
  return payload_.command_;
}
inline ::railway::TrainCommand* Message::mutable_command() {
  // @@protoc_insertion_point(field_mutable:railway.Message.command)
  return _internal_mutable_command();
}

// .railway.TrainStatus status = 2;
inline bool Message::_internal_has_status() const {
  return payload_case() == kStatus;
}
inline bool Message::has_status() const {
  return _internal_has_status();
}
inline void Message::set_has_status() {
  _oneof_case_[0] = kStatus;
}
inline void Message::clear_status() {
  if (_internal_has_status()) {
    if (GetArena() == nullptr) {
      delete payload_.status_;
    }
    clear_has_payload();
  }
}
inline ::railway::TrainStatus* Message::release_status() {
  // @@protoc_insertion_point(field_release:railway.Message.status)
  if (_internal_has_status()) {
    clear_has_payload();
      ::railway::TrainStatus* temp = payload_.status_;
    if (GetArena() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    payload_.status_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::railway::TrainStatus& Message::_internal_status() const {
  return _internal_has_status()
      ? *payload_.status_
      : *reinterpret_cast< ::railway::TrainStatus*>(&::railway::_TrainStatus_default_instance_);
}
inline const ::railway::TrainStatus& Message::status() const {
  // @@protoc_insertion_point(field_get:railway.Message.status)
  return _internal_status();
}
inline ::railway::TrainStatus* Message::unsafe_arena_release_status() {
  // @@protoc_insertion_point(field_unsafe_arena_release:railway.Message.status)
  if (_internal_has_status()) {
    clear_has_payload();
    ::railway::TrainStatus* temp = payload_.status_;
    payload_.status_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Message::unsafe_arena_set_allocated_status(::railway::TrainStatus* status) {
  clear_payload();
  if (status) {
    set_has_status();
    payload_.status_ = status;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:railway.Message.status)
}
inline ::railway::TrainStatus* Message::_internal_mutable_status() {
  if (!_internal_has_status()) {
    clear_payload();
    set_has_status();
    payload_.status_ = CreateMaybeMessage< ::railway::TrainStatus >(GetArena());
  }
  return payload_.status_;
}
inline ::railway::TrainStatus* Message::mutable_status() {
  // @@protoc_insertion_point(field_mutable:railway.Message.status)
  return _internal_mutable_status();
}

inline bool Message::has_payload() const {
  return payload_case() != PAYLOAD_NOT_SET;
}
inline void Message::clear_has_payload() {
  _oneof_case_[0] = PAYLOAD_NOT_SET;
}
inline Message::PayloadCase Message::payload_case() const {
  return Message::PayloadCase(_oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace railway

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::railway::TrainCommand_CommandType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::railway::TrainCommand_CommandType>() {
  return ::railway::TrainCommand_CommandType_descriptor();
}
template <> struct is_proto_enum< ::railway::TrainStatus_StatusCode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::railway::TrainStatus_StatusCode>() {
  return ::railway::TrainStatus_StatusCode_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_messages_2eproto
