# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages.proto',
  package='railway',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0emessages.proto\x12\x07railway\"\xc5\x01\n\x0cTrainCommand\x12\x10\n\x08train_id\x18\x01 \x01(\t\x12\x32\n\x07\x63ommand\x18\x02 \x01(\x0e\x32!.railway.TrainCommand.CommandType\x12\x14\n\x0ctarget_speed\x18\x03 \x01(\x01\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"F\n\x0b\x43ommandType\x12\x0e\n\nACCELERATE\x10\x00\x12\t\n\x05\x42RAKE\x10\x01\x12\x08\n\x04STOP\x10\x02\x12\x12\n\x0e\x45MERGENCY_STOP\x10\x03\"\xdf\x01\n\x0bTrainStatus\x12\x10\n\x08train_id\x18\x01 \x01(\t\x12\x15\n\rcurrent_speed\x18\x02 \x01(\x01\x12\x10\n\x08position\x18\x03 \x01(\x01\x12/\n\x06status\x18\x04 \x01(\x0e\x32\x1f.railway.TrainStatus.StatusCode\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\x12\x10\n\x08warnings\x18\x06 \x03(\t\"?\n\nStatusCode\x12\n\n\x06NORMAL\x10\x00\x12\x0b\n\x07WARNING\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x12\r\n\tEMERGENCY\x10\x03\"f\n\x07Message\x12(\n\x07\x63ommand\x18\x01 \x01(\x0b\x32\x15.railway.TrainCommandH\x00\x12&\n\x06status\x18\x02 \x01(\x0b\x32\x14.railway.TrainStatusH\x00\x42\t\n\x07payloadb\x06proto3'
)



_TRAINCOMMAND_COMMANDTYPE = _descriptor.EnumDescriptor(
  name='CommandType',
  full_name='railway.TrainCommand.CommandType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ACCELERATE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BRAKE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EMERGENCY_STOP', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=155,
  serialized_end=225,
)
_sym_db.RegisterEnumDescriptor(_TRAINCOMMAND_COMMANDTYPE)

_TRAINSTATUS_STATUSCODE = _descriptor.EnumDescriptor(
  name='StatusCode',
  full_name='railway.TrainStatus.StatusCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NORMAL', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WARNING', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EMERGENCY', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=388,
  serialized_end=451,
)
_sym_db.RegisterEnumDescriptor(_TRAINSTATUS_STATUSCODE)


_TRAINCOMMAND = _descriptor.Descriptor(
  name='TrainCommand',
  full_name='railway.TrainCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='train_id', full_name='railway.TrainCommand.train_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='command', full_name='railway.TrainCommand.command', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='target_speed', full_name='railway.TrainCommand.target_speed', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='railway.TrainCommand.timestamp', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TRAINCOMMAND_COMMANDTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=225,
)


_TRAINSTATUS = _descriptor.Descriptor(
  name='TrainStatus',
  full_name='railway.TrainStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='train_id', full_name='railway.TrainStatus.train_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='current_speed', full_name='railway.TrainStatus.current_speed', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position', full_name='railway.TrainStatus.position', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='railway.TrainStatus.status', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='railway.TrainStatus.timestamp', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='warnings', full_name='railway.TrainStatus.warnings', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TRAINSTATUS_STATUSCODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=228,
  serialized_end=451,
)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='railway.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='railway.Message.command', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='railway.Message.status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='railway.Message.payload',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=453,
  serialized_end=555,
)

_TRAINCOMMAND.fields_by_name['command'].enum_type = _TRAINCOMMAND_COMMANDTYPE
_TRAINCOMMAND_COMMANDTYPE.containing_type = _TRAINCOMMAND
_TRAINSTATUS.fields_by_name['status'].enum_type = _TRAINSTATUS_STATUSCODE
_TRAINSTATUS_STATUSCODE.containing_type = _TRAINSTATUS
_MESSAGE.fields_by_name['command'].message_type = _TRAINCOMMAND
_MESSAGE.fields_by_name['status'].message_type = _TRAINSTATUS
_MESSAGE.oneofs_by_name['payload'].fields.append(
  _MESSAGE.fields_by_name['command'])
_MESSAGE.fields_by_name['command'].containing_oneof = _MESSAGE.oneofs_by_name['payload']
_MESSAGE.oneofs_by_name['payload'].fields.append(
  _MESSAGE.fields_by_name['status'])
_MESSAGE.fields_by_name['status'].containing_oneof = _MESSAGE.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['TrainCommand'] = _TRAINCOMMAND
DESCRIPTOR.message_types_by_name['TrainStatus'] = _TRAINSTATUS
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TrainCommand = _reflection.GeneratedProtocolMessageType('TrainCommand', (_message.Message,), {
  'DESCRIPTOR' : _TRAINCOMMAND,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:railway.TrainCommand)
  })
_sym_db.RegisterMessage(TrainCommand)

TrainStatus = _reflection.GeneratedProtocolMessageType('TrainStatus', (_message.Message,), {
  'DESCRIPTOR' : _TRAINSTATUS,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:railway.TrainStatus)
  })
_sym_db.RegisterMessage(TrainStatus)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:railway.Message)
  })
_sym_db.RegisterMessage(Message)


# @@protoc_insertion_point(module_scope)
